version: "3.7"
services:
  proxy:
    image: "traefik:2.2"
    command:
      - "--api.debug=true"
      - "--log.level=DEBUG"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesResolvers.le.acme.email=me@hacks.pro.br"
      - "--certificatesResolvers.le.acme.storage=/acme/acme.json"
      - "--certificatesResolvers.le.acme.tlschallenge=true"
    ports:
      - target: 80
        published: 80
      - target: 443
        published: 443
    volumes:
      - acme:/acme/
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        #- "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
        #- "traefik.http.routers.http-catchall.entrypoints=web"
        #- "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
        #- "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  whoami:
    image: containous/whoami
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role == worker
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami_http.rule=hostregexp(`${Host:.+}`)"
        - "traefik.http.routers.whoami_http.entrypoints=web"
        - "traefik.http.routers.whoami_http.middlewares=redirect-to-https"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

        - "traefik.http.routers.whoami.rule=Host(`${DOMAIN}`)"
        - "traefik.http.routers.whoami.entrypoints=websecure"
        - "traefik.http.routers.whoami.tls=true"
        - "traefik.http.routers.whoami.tls.certresolver=le"

        - "traefik.http.services.whoami.loadbalancer.server.port=80"

volumes:
  acme:
