version: "3.7"
services:
  whoami:
    image: containous/whoami
    networks:
      - proxy
    deploy:
      replicas: 2
      labels:
        - "traefik.enable=true""
        - "traefik.http.services.whoami.loadbalancer.server.port=80"
        - "traefik.http.routers.whoami.rule=Host(`${DOMAIN}`)"
        - "traefik.http.routers.whoami.entrypoints=web"
networks:
  proxy:
    external: true
